// Test generated by RoostGPT for test dummy-test using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

public class StudentJdbcRepository_deleteById29a6c3df2fTest {

    @InjectMocks
    private StudentJdbcRepository studentJdbcRepository;

    @Mock
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testDeleteById_success() {
        long id = 1L;
        studentJdbcRepository.deleteById(id);
        verify(jdbcTemplate, times(1)).update("delete from student where id=?", id);
    }

    @Test
    public void testDeleteById_invalidId() {
        long id = -1L;
        studentJdbcRepository.deleteById(id);
        verify(jdbcTemplate, times(1)).update("delete from student where id=?", id);
    }
}