// Test generated by RoostGPT for test dummy-test using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@Repository
public class StudentJdbcRepository_update40cb1dc622Test {

    @InjectMocks
    private StudentJdbcRepository studentJdbcRepository;

    @Mock
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testUpdateSuccess() {
        Student student = new Student(1, "John Doe", "A1234567");
        when(jdbcTemplate.update("update student set name = ?, passport_number = ? where id = ?",
                student.getName(), student.getPassportNumber(), student.getId())).thenReturn(1);

        int result = studentJdbcRepository.update(student);
        assertEquals(1, result, "Update should return 1 on successful update");
    }

    @Test
    public void testUpdateFailure() {
        Student student = new Student(1, "John Doe", "A1234567");
        when(jdbcTemplate.update("update student set name = ?, passport_number = ? where id = ?",
                student.getName(), student.getPassportNumber(), student.getId())).thenReturn(0);

        int result = studentJdbcRepository.update(student);
        assertEquals(0, result, "Update should return 0 on failed update");
    }
}