// Test generated by RoostGPT for test dummy-test using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setIde5ec36044aTest {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetId_positiveValue() {
        Long expectedId = 1L;
        student.setId(expectedId);
        assertEquals(expectedId, student.getId(), "Student ID should be set to the given positive value");
    }

    @Test
    public void testSetId_nullValue() {
        Long expectedId = null;
        student.setId(expectedId);
        assertEquals(expectedId, student.getId(), "Student ID should be set to null");
    }
}