// Test generated by RoostGPT for test dummy-test using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_getPassportNumberaa3bc55c5bTest {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testGetPassportNumber_validPassportNumber() {
        String expectedPassportNumber = "P12345678";
        student.setPassportNumber(expectedPassportNumber);
        String actualPassportNumber = student.getPassportNumber();
        assertEquals(expectedPassportNumber, actualPassportNumber, "Passport number should match the expected value");
    }

    @Test
    public void testGetPassportNumber_emptyPassportNumber() {
        String expectedPassportNumber = "";
        student.setPassportNumber(expectedPassportNumber);
        String actualPassportNumber = student.getPassportNumber();
        assertEquals(expectedPassportNumber, actualPassportNumber, "Passport number should be empty");
    }
}