// Test generated by RoostGPT for test dummy-test using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setPassportNumber8bba5b77d0Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetPassportNumber_ValidPassportNumber() {
        String validPassportNumber = "A12345678";
        student.setPassportNumber(validPassportNumber);
        assertEquals(validPassportNumber, student.getPassportNumber(), "Passport number should be set correctly");
    }

    @Test
    public void testSetPassportNumber_NullPassportNumber() {
        student.setPassportNumber(null);
        assertEquals(null, student.getPassportNumber(), "Passport number should be set to null");
    }
}