// Test generated by RoostGPT for test dummy-test using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class Student_Studentb2349b4fdbTest {

    @Test
    public void testStudentConstructor() {
        Student student = new Student();
        assertNotNull(student, "Student object should not be null");
    }

    @Test
    public void testStudentConstructorWithParameters() {
        Student student = new Student(1, "John Doe", "A1234567");
        assertNotNull(student, "Student object should not be null");
        assertEquals(1, student.getId(), "Student ID should match");
        assertEquals("John Doe", student.getName(), "Student name should match");
        assertEquals("A1234567", student.getPassportNumber(), "Student passport number should match");
    }

}