// Test generated by RoostGPT for test dummy-test using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_toString6ab14901b5Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testToString_WithValidData() {
        // TODO: Replace the sample values with real data
        student.setId(1);
        student.setName("John Doe");
        student.setPassportNumber("A1234567");

        String expectedOutput = "Student [id=1, name=John Doe, passportNumber=A1234567]";
        assertEquals(expectedOutput, student.toString());
    }

    @Test
    public void testToString_WithEmptyData() {
        student.setId(0);
        student.setName("");
        student.setPassportNumber("");

        String expectedOutput = "Student [id=0, name=, passportNumber=]";
        assertEquals(expectedOutput, student.toString());
    }
}