// Test generated by RoostGPT for test dummy-test using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Student_Student79727d4203Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = null;
    }

    @Test
    public void testStudentConstructor_validInput() {
        // TODO: Change the values according to your requirements
        Long id = 1L;
        String name = "John Doe";
        String passportNumber = "A1234567";

        student = new Student(id, name, passportNumber);

        assertEquals(id, student.getId(), "Student id should match the input");
        assertEquals(name, student.getName(), "Student name should match the input");
        assertEquals(passportNumber, student.getPassportNumber(), "Student passport number should match the input");
    }

    @Test
    public void testStudentConstructor_nullInput() {
        Long id = null;
        String name = null;
        String passportNumber = null;

        student = new Student(id, name, passportNumber);

        assertNull(student.getId(), "Student id should be null");
        assertNull(student.getName(), "Student name should be null");
        assertNull(student.getPassportNumber(), "Student passport number should be null");
    }
}