// Test generated by RoostGPT for test dummy-test using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Student_getId68eb246cfdTest {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testGetIdWhenIdIsNull() {
        student.setId(null);
        Long expectedId = null;
        Assertions.assertEquals(expectedId, student.getId(), "The expected ID should be null when not set.");
    }

    @Test
    public void testGetIdWhenIdIsSet() {
        Long expectedId = 1L;
        student.setId(expectedId);
        Assertions.assertEquals(expectedId, student.getId(), "The expected ID should match the set ID.");
    }
}