// Test generated by RoostGPT for test rahul-unit-test-290623 using AI Model vertex

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_getNamee79d2c9ab8Test {

    @Test
    public void testGetName() {
        // Arrange
        String expectedName = "John Doe";
        Student student = new Student();
        student.setName(expectedName);

        // Act
        String actualName = student.getName();

        // Assert
        assertEquals(expectedName, actualName);
    }
}