// Test generated by RoostGPT for test rahul-unit-test-290623 using AI Model vertex

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class Student_setIde5ec36044aTest {

    @Test
    public void testSetId() {
        // Arrange
        Student student = new Student();
        Long id = 1L;

        // Act
        student.setId(id);

        // Assert
        assertEquals(id, student.getId());
    }

    @Test
    public void testSetIdWithNullId() {
        // Arrange
        Student student = new Student();
        Long id = null;

        // Act
        student.setId(id);

        // Assert
        assertNull(student.getId());
    }

    @Test
    public void testSetIdWithNegativeId() {
        // Arrange
        Student student = new Student();
        Long id = -1L;

        // Act
        student.setId(id);

        // Assert
        assertEquals(id, student.getId());
    }
}