// Test generated by RoostGPT for test rahul-unit-test-290623 using AI Model vertex

package com.in28minutes.springboot.rest.example.student;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

import java.util.Optional;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import com.in28minutes.springboot.rest.example.student.Student;
import com.in28minutes.springboot.rest.example.student.StudentNotFoundException;
import com.in28minutes.springboot.rest.example.student.StudentRepository;
import com.in28minutes.springboot.rest.example.student.StudentResource;

@RunWith(MockitoJUnitRunner.class)
public class StudentResource_retrieveStudent9c2c90d0abTest {

    @Mock
    private StudentRepository studentRepository;

    @InjectMocks
    private StudentResource studentResource;

    private Student student;

    @Before
    public void setUp() {
        student = new Student();
        student.setId(1L);
        student.setName("John Doe");
    }

    @Test
    public void testRetrieveStudent_success() {
        when(studentRepository.findById(1L)).thenReturn(Optional.of(student));

        Student retrievedStudent = studentResource.retrieveStudent(1L);

        assertEquals(student, retrievedStudent);
    }

    @Test(expected = StudentNotFoundException.class)
    public void testRetrieveStudent_notFound() {
        when(studentRepository.findById(1L)).thenReturn(Optional.empty());

        studentResource.retrieveStudent(1L);
    }
}