// Test generated by RoostGPT for test rahul-unit-test-290623 using AI Model vertex

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setPassportNumber8bba5b77d0Test {

    @Test
    public void testSetPassportNumber() {
        // Arrange
        Student student = new Student();
        String passportNumber = "1234567890";

        // Act
        student.setPassportNumber(passportNumber);

        // Assert
        assertEquals(passportNumber, student.getPassportNumber());
    }
}