// Test generated by RoostGPT for test rahul-unit-test-290623 using AI Model vertex

package com.in28minutes.springboot.rest.example.student;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.util.List;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import com.in28minutes.springboot.rest.example.student.Student;
import com.in28minutes.springboot.rest.example.student.StudentRepository;

@RunWith(SpringRunner.class)
@SpringBootTest
public class StudentResource_retrieveAllStudents20c77fb2dcTest {

    @Autowired
    private StudentRepository studentRepository;

    @Test
    public void testRetrieveAllStudents() {
        List<Student> students = studentRepository.findAll();
        assertNotNull(students);
        assertEquals(2, students.size());
    }
}