// Test generated by RoostGPT for test rahul-unit-test-290623 using AI Model vertex

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class Student_Student79727d4203Test {

    @Test
    public void testConstructor() {
        Long id = 1L;
        String name = "John Doe";
        String passportNumber = "123456789";

        Student student = new Student(id, name, passportNumber);

        assertEquals(id, student.getId());
        assertEquals(name, student.getName());
        assertEquals(passportNumber, student.getPassportNumber());
    }

}