// Test generated by RoostGPT for test rahul-unit-test-290623 using AI Model vertex

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class Student_getPassportNumberaa3bc55c5bTest {

    @Test
    public void test_getPassportNumber_success() {
        // Arrange
        String expectedPassportNumber = "1234567890";
        Student student = new Student();
        student.setPassportNumber(expectedPassportNumber);

        // Act
        String actualPassportNumber = student.getPassportNumber();

        // Assert
        assertEquals(expectedPassportNumber, actualPassportNumber);
    }

    @Test
    public void test_getPassportNumber_failure() {
        // Arrange
        String expectedPassportNumber = "1234567890";
        Student student = new Student();

        // Act
        String actualPassportNumber = student.getPassportNumber();

        // Assert
        assertNotEquals(expectedPassportNumber, actualPassportNumber);
    }
}