// Test generated by RoostGPT for test rahul-unit-test-290623 using AI Model vertex

package com.in28minutes.springboot.rest.example.student;

import static org.junit.jupiter.api.Assertions.*;

import java.net.URI;
import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

@SpringBootTest
public class StudentResource_deleteStudent4580da98e2Test {

    @Autowired
    private StudentRepository studentRepository;

    @Test
    public void testDeleteStudent() {
        // Given
        Student student = new Student();
        student.setId(1L);
        student.setName("John Doe");
        studentRepository.save(student);

        // When
        studentRepository.deleteById(student.getId());

        // Then
        Optional<Student> studentOptional = studentRepository.findById(student.getId());
        assertFalse(studentOptional.isPresent());
    }
}